/**
 * This file is autogenerated by Payload CMS.
 * DO NOT MODIFY IT BY HAND.
 */

export interface Config {
  auth: {
    users: UsersAuthOperations
  }
  collections: {
    users: User
    pages: Page
    media: Media
    'audit-logs': AuditLog
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    pages: PagesSelect<false> | PagesSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>
  }
  db: {
    defaultIDType: string
  }
  globals: {}
  globalsSelect: {}
  locale: null
  user: User & {
    collection: 'users'
  }
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}

export interface UsersAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}

export interface User {
  id: string
  email: string
  role: 'admin' | 'editor' | 'viewer'
  updatedAt: string
  createdAt: string
}

export interface Page {
  id: string
  title: string
  slug: string
  status?: 'draft' | 'published'
  publishedAt?: string
  content?: Array<HeroBlock | FeaturesBlock | CTABlock | ContactFormBlock | RichTextBlock>
  seo?: {
    title?: string
    description?: string
    keywords?: string
    ogImage?: string | Media
  }
  updatedAt: string
  createdAt: string
}

export interface HeroBlock {
  blockType: 'hero'
  title: string
  subtitle?: string
  cta?: {
    label: string
    url: string
  }
  backgroundImage?: string | Media
}

export interface FeaturesBlock {
  blockType: 'features'
  title?: string
  features?: Array<{
    title: string
    description: string
    icon?: string | Media
  }>
}

export interface CTABlock {
  blockType: 'cta'
  title: string
  description?: string
  primaryCTA?: {
    label: string
    url: string
  }
  secondaryCTA?: {
    label: string
    url: string
  }
  backgroundColor?: 'blue' | 'gray'
}

export interface ContactFormBlock {
  blockType: 'contactForm'
  title?: string
  description?: string
  fields?: Array<{
    name: string
    label: string
    type: 'text' | 'email' | 'tel' | 'textarea'
    placeholder?: string
    required?: boolean
  }>
}

export interface RichTextBlock {
  blockType: 'richText'
  content?: any
}

export interface Media {
  id: string
  alt?: string
  url?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
  updatedAt: string
  createdAt: string
}

export interface AuditLog {
  id: string
  collection: string
  documentId: string
  action: 'create' | 'update' | 'delete'
  user?: string | User
  changes?: any
  timestamp: string
  updatedAt: string
  createdAt: string
}

// Select types
export interface UsersSelect<T extends boolean = true> {
  email?: T
  role?: T
  updatedAt?: T
  createdAt?: T
}

export interface PagesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  status?: T
  publishedAt?: T
  content?: T
  seo?: T
  updatedAt?: T
  createdAt?: T
}

export interface MediaSelect<T extends boolean = true> {
  alt?: T
  url?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  updatedAt?: T
  createdAt?: T
}

export interface AuditLogsSelect<T extends boolean = true> {
  collection?: T
  documentId?: T
  action?: T
  user?: T
  changes?: T
  timestamp?: T
  updatedAt?: T
  createdAt?: T
}
